---
title: "Missing Water Assessment"
author: Zachary M. Smith
output: html_notebook
---

```{r}
lagk.sub <- lagk.df %>% 
  select(site, date_time, flow) %>% 
  filter(site %in% c("lfalls", "predicted"),
         date_time >= "1995-01-01") %>%
  mutate(year = year(date_time),
         month = month(date_time, label = TRUE)) %>% 
  distinct()
```



```{r}
lagk.wide <- lagk.df %>%
  select(date_time, site, flow) %>% 
  group_by(date_time, site) %>% 
  summarize(flow = mean(flow, na.rm = TRUE)) %>% 
  spread(site, flow) %>% 
  mutate(residuals = predicted - lfalls,
         year = year(date_time)) %>% 
  select(date_time, year, month, residuals)
```

```{r}
ggplot(lagk.wide, aes(date_time, residuals)) +
  geom_line()
```

```{r fig.width=10, fig.height=20}
ggplot(lagk.wide, aes(date_time, residuals)) +
  geom_line() +
  facet_wrap(~year, ncol = 2, scales = "free")
```


```{r}
resid.pos <- lagk.wide %>% 
  mutate(month = month(date_time, label = TRUE)) %>% 
  #filter(residuals > 0) %>% 
  group_by(month) %>% 
  summarize(mean = mean(residuals, na.rm = TRUE),
            sd = sd(residuals, na.rm = TRUE),
            median = median(residuals, na.rm = TRUE))
```

```{r}
ggplot(resid.pos, aes(month, mean)) +
  geom_bar(stat = "identity") +
   geom_errorbar(aes(ymin = mean - sd, ymax = mean + sd),
                  width = 0.2,                    # Width of the error bars
                  position = position_dodge(0.9))
```


