---
title: "R Notebook"
output: html_notebook
---

```{r}
lagk.sub <- lagk.df %>% 
  select(site, date_time, flow) %>% 
  filter(site %in% c("lfalls", "predicted"),
         date_time >= "1995-01-01") %>%
  mutate(year = year(date_time),
         month = month(date_time, label = TRUE)) %>% 
  distinct()
```


```{r}

```



```{r fig.width=10, fig.height=40}
ggplot(lagk.sub, aes(date_time, log(flow, base = 10), group = site)) +
  geom_line(aes(color = site), size = 1, alpha = 0.5) +
  scale_x_datetime(date_labels = "%b",
                   date_breaks = "1 month") +
  facet_wrap(~year, ncol = 1, scale = "free")
```

```{r fig.width=10, fig.height=40}
lagk.sub %>% 
  filter(month %in% c("Jun", "Jul", "Aug")) %>% 
ggplot(aes(date_time, flow, group = site)) +
  geom_line(aes(color = site), size = 1, alpha = 0.5) +
  coord_cartesian(xlim = NULL, ylim = c(0,7000)) +
  scale_x_datetime(date_labels = "%b",
                   date_breaks = "1 month") +
  facet_wrap(~year, ncol = 1, scale = "free")
```

```{r}
lagk.resid <- lagk.sub %>%
  group_by(date_time, site, year, month) %>% 
  summarize(flow = mean(flow, na.rm = TRUE)) %>%
  ungroup() %>% 
  spread(site, flow) %>% 
  mutate(residuals = predicted - lfalls,
         #flow_bins = cut(lfalls, breaks = seq(0, 100000, 500)))
         flow_bins = ntile(lfalls, 4)) %>% 
  filter(!is.na(flow_bins)) %>% 
  group_by(flow_bins) %>% 
  mutate(bin = paste(min(lfalls, na.rm = TRUE), max(lfalls, na.rm = TRUE), sep = " - "))
         
```

```{r}
test <- lagk.resid %>% 
  mutate(positive = if_else(residuals > 0, TRUE, FALSE))

test2 <- rle(test$positive)$lengths
test3 <- lapply(test2, function(x) rep(jitter(x), 1, x)) %>% unlist()
test <- test %>% 
  ungroup() %>% 
  mutate(test2 = test3,
         days = paste(test2 %/% 24, "Days and", round(test2 %% 24, 1), "Hours"))

test4 <- test %>% 
  filter(positive == TRUE)
```

```{r fig.width=10, fig.height=80}
test5 <- test4 %>% 
  filter(test2 > 168) %>% # 7 days
  select(date_time, test2, days, lfalls, predicted) %>% 
  gather(site, flow, lfalls:predicted) %>% 
  arrange(test2, date_time) %>% 
  mutate(days = factor(days, levels = unique(days)))

ggplot(test5, aes(date_time, flow, group = site, color = site)) +
  geom_line() +
  scale_x_datetime(date_labels = "%b %d, %Y") +
  facet_wrap(~days, ncol = 1, scales = "free")
```




```{r fig.width=10, fig.height=40}
ggplot(lagk.resid, aes(date_time, residuals)) +
  geom_line(size = 1) +
  scale_x_datetime(date_labels = "%b",
                   date_breaks = "1 month") +
  facet_wrap(~year, ncol = 1, scale = "free")
```

```{r}
lagk.resid.monthly <- lagk.resid %>% 
  group_by(month) %>% 
  summarize(mean = mean(residuals, na.rm = TRUE),
            sd = sd(residuals, na.rm = TRUE),
            median = median(residuals, na.rm = TRUE)) %>% 
  mutate(mean_direction = case_when(
    mean > 0 ~ "positive",
    mean < 0 ~ "negative",
    TRUE ~ "equal"
  ))
```


```{r}
ggplot(lagk.resid.monthly, aes(month, mean)) +
  geom_bar(stat = "identity") +
   geom_errorbar(aes(ymin = mean - sd, ymax = mean + sd),
                  width = 0.2,
                  position = position_dodge(0.9)) +
  xlab("") +
  ylab("Mean Residuals")
```

```{r}
lagk.resid.monthly <- lagk.resid %>% 
  group_by(month, bin) %>% 
  summarize(mean = mean(residuals, na.rm = TRUE),
            sd = sd(residuals, na.rm = TRUE),
            median = median(residuals, na.rm = TRUE)) %>% 
  mutate(mean_direction = case_when(
    mean > 0 ~ "positive",
    mean < 0 ~ "negative",
    TRUE ~ "equal"
  ))
```

```{r fig.width=10, fig.height=5}
#fig.width=10, fig.height=120
lagk.resid.monthly %>% 
  filter(!is.na(bin)) %>% 
 mutate(test = as.numeric(gsub( " .*$", "", bin))) %>% 
  arrange(test) %>% 
  mutate(bin = factor(bin, levels = unique(.$bin))) %>% 
ggplot(aes(month, mean, fill = mean_direction)) +
  scale_fill_manual(values = c("#E69F00", "#56B4E9", "#999999")) +
  geom_bar(stat = "identity") +
   geom_errorbar(aes(ymin = mean - sd, ymax = mean + sd),
                  width = 0.2,
                  position = position_dodge(0.9)) +
  xlab("") +
  ylab("Mean Residuals") +
  facet_wrap(~bin, ncol = 2)
```

```{r fig.width=10, fig.height=5}
#fig.width=10, fig.height=120
lagk.resid.monthly %>% 
  filter(!is.na(bin)) %>% 
 mutate(test = as.numeric(gsub( " .*$", "", bin))) %>% 
  arrange(test) %>% 
  mutate(bin = factor(bin, levels = unique(.$bin))) %>% 
ggplot(aes(month, mean, fill = mean_direction)) +
  scale_fill_manual(values = c("#E69F00", "#56B4E9", "#999999")) +
  geom_bar(stat = "identity") +
   geom_errorbar(aes(ymin = mean - sd, ymax = mean + sd),
                  width = 0.2,
                  position = position_dodge(0.9)) +
  xlab("") +
  ylab("Mean Residuals") +
  facet_wrap(~bin, ncol = 2, scale = "free")
```

## Regression

### Observed vs. Predicted

```{r fig.width=10, fig.height=6}
ggplot(lagk.resid, aes(lfalls, predicted)) +
  geom_point(alpha = 0.25) +
  geom_abline(slope = 1, size = 3, color = "red", alpha = 0.75)
```

```{r fig.width=10, fig.height=20}
lagk.resid %>% 
ggplot(aes(lfalls, predicted)) +
  geom_point(alpha = 0.25) +
  geom_abline(slope = 1, size = 2, color = "red", alpha = 0.5) +
  geom_smooth(method='lm',formula=y~x, size = 2, color = "blue") +
  facet_wrap(~year, ncol = 2, scale = "free")
```




### Observed vs. Residuals

```{r fig.width=10, fig.height=6}
ggplot(lagk.resid, aes(lfalls, residuals)) +
  geom_point(alpha = 0.25)
```
